### ISSUE TITLE
Milestone Alpha check List

### ISSUE THREAD

**Issue by yoitsukizuna** [scr26/CS490-Project#2]
- [ ] Everyone pls commit to github HERE;
- [ ] Create login form
- [ ] Create user restriction form
- [ ] create database
- [ ] create landing page for user
- [ ] create Administrator landing page
- [ ] create Administrator login page
- [ ] finish frontend, link database to response with registeration
