### ISSUE TITLE
Milestone Beta Checklist

### ISSUE THREAD

**Issue by yoitsukizuna** [scr26/CS490-Project#3]
- [ ] make posts
- [ ] users can edit and delete his own posts
- [ ] users can comment on others posts
- [ ] search for posts
- [ ] search for users
- [ ] real time chat function   -socketio?
- [ ]
